### ISSUE TITLE
IExecDataProtector may be initialized with an undefined provider

### ISSUE THREAD

**Issue by PierreJeanjacquot** [TalentLayer-Labs/starter-kit#28]
https://github.com/TalentLayer-Labs/starter-kit/blob/e20f239402017c2d270d2b60f3b02d04b3031a0e/src/modules/Web3mail/context/web3mail.tsx#L70C64-L70C64

here `provider2` may be undefined this will cause an error when instantiating `new IExecDataProtector(povider2)`

**Comment by 0xRomain** [comment]
Note: The problem was link to account.isConnected which is true while reconnecting and at this moment connector is undefined

Commit Fix: https://github.com/TalentLayer-Labs/starter-kit/commit/986bfa008b81c15ca25f4f93f9ccb88d6defa4a4
